service: libre
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  parse:
    handler: bin/parse
    environment:
      BASE_URL: ${env:BASE_URL}
      USERNAME: ${env:USERNAME}
      PASSWORD: ${env:PASSWORD}
    events:
      - schedule: rate(2 hours)
