service: libre
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Scan"
      Resource:
        Fn::GetAtt:
          - DynamoDBTable
          - Arn
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource:
        Ref: NotificationTopic

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  parse:
    handler: bin/parse
    environment:
      BASE_URL: ${env:BASE_URL}
      USERNAME: ${env:USERNAME}
      PASSWORD: ${env:PASSWORD}
      DYNAMODB_TABLE:
        Ref: DynamoDBTable
    events:
      - schedule: rate(2 hours)
  check:
    handler: bin/check
    environment:
      DYNAMODB_TABLE:
        Ref: DynamoDBTable
      SNS_TOPIC_ARN:
        Ref: NotificationTopic
    events:
      - schedule: cron(0 8 * * ? *)
      - schedule: cron(0 16 * * ? *)

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: libre
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
    NotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Libre
        Subscription:
          - Endpoint: till.kahlbrock@gmail.com
            Protocol: email